version: '3.8'

services:
  dockerdemo:
    image: dockerdemo
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Development
      - DISPLAY=:99
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:80"
      - "6080:6080"  # VNC web access port
    volumes:
      - ../:/workspaces:cached
      - /var/run/docker.sock:/var/run/docker.sock
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    init: true