version: '3.8'

services:
  dockerdemo:
    image: dockerdemo
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Development
      - DISPLAY=:99
    ports:
      - "8080:80"
      - "6080:6080"  # VNC web access port
    volumes:
      - .:/src
      - /tmp/.X11-unix:/tmp/.X11-unix
    privileged: true